services: 
  app:
    image: node:alpine
    # build: 
    #   context: .
    #   dockerfile: Dockerfile.minhaImagem
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    volumes:
      - ./.data/redis:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  postgres:
    image: postgres:alpine
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  #  ports:
  #     - 5433:5432
